<a href="https://colab.research.google.com/github/kellybianca/DL-2021.1/blob/main/src/numpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Questions on NumPy Array


##### How to create an empty and a full NumPy array?







In [ ]:
import numpy as np

empty = np.empty((3, 4), dtype=int)
print('Empty array: ', empty)

full = np.full([3, 3], 55, dtype=int)
print('\n\n Full array: ', full)

Empty array:  [[ 1  2  3  4]
 [ 6 23  8  2]
 [ 7  1  8  3]]


 Full array:  [[55 55 55]
 [55 55 55]
 [55 55 55]]


##### Create a Numpy array filled with all zeros

In [ ]:
import numpy as np

np.zeros((4), dtype=np.int)

array([0, 0, 0, 0])

##### Create a Numpy array filled with all ones


In [ ]:
import numpy as np

np.ones((5), dtype=np.int)

array([1, 1, 1, 1, 1])

##### Check whether a Numpy array contains a specified row







In [ ]:
import numpy as np

array = np.array([[1,2,3,4],[6,23,8,2],[7,1,8,3]])

print([1,2,3,4] in array.tolist())
print([6,23,8,2] in array.tolist())
print([7,1,8,10] in array.tolist())
print([1,2,3,4,5] in array.tolist())

True
True
False
False


##### How to Remove rows in Numpy array that contains non-numeric values?

In [ ]:
import numpy as np

array = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Array before remove: \n", array)
  
print("\nArray after remove non-numeric values: \n",array[~np.isnan(array).any(axis=1)] )

Array before remove: 
 [[10.5 22.5  3.8]
 [41.   nan  nan]]

Array after remove non-numeric values: 
 [[10.5 22.5  3.8]]


##### Remove single-dimensional entries from the shape of an array.

 Ref.: [NumpySqueeze](https://www.geeksforgeeks.org/numpy-squeeze-in-python/)

In [ ]:
import numpy as geek

# axis : Selects a subset of the single-dimensional entries in the shape. 

in_arr = geek.arange(9).reshape(1, 3, 3) 
print ("Input array: \n", in_arr)  

out_arr = geek.squeeze(in_arr, axis = 0) 
print ("\nOutput array: \n", out_arr)  

print("\nThe shapes of Input: ",in_arr.shape, "and Output: ", out_arr.shape) 

Input array: 
 [[[0 1 2]
  [3 4 5]
  [6 7 8]]]

Output array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

The shapes of Input:  (1, 3, 3) and Output:  (3, 3)


##### Find the number of occurrences of a sequence in a NumPy array



In [ ]:
import numpy as np

array = np.array([[2, 8, 9, 4], [9, 4, 9, 4], [4, 5, 9, 7], [2, 9, 4, 3]])
  
output = repr(array).count("9, 4")

print("Occurrences: ",output)

Occurrences:  4


##### Find the most frequent value in a NumPy array


In [ ]:
import numpy as np

x = np.array([1,2,3,4,5,1,2,3,3,2,1,2,4,5,2,2,3])
print("Original array: \n", x)
  
print("\nMost frequent value: ", np.bincount(x).argmax())

Original array: 
 [1 2 3 4 5 1 2 3 3 2 1 2 4 5 2 2 3]

Most frequent value:  2


##### Combining a one and a two-dimensional NumPy Array


In [ ]:
import numpy as np
  
array_1d = np.arange(5)
print("One dimensional array: \n", array_1d)
  
array_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array: \n", array_2d)

print("\nCombination with both arrays: ")
for a, b in np.nditer([array_1d, array_2d]):
    print("\t%d:%d" % (a, b),)

One dimensional array: 
 [0 1 2 3 4]

Two dimensional array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Combination with both arrays: 
	0:0
	1:1
	2:2
	3:3
	4:4
	0:5
	1:6
	2:7
	3:8
	4:9


##### How to build an array of all combinations of two NumPy arrays?

In [ ]:
import numpy as np
  
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
  
print("Array 1: ", array_1)
  
print("\nArray 2: ", array_2) 

combination = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
  
print("\nCombination with both arrays: \n", combination)

Array 1:  [1 2]

Array 2:  [4 6]

Combination with both arrays: 
 [[1 4]
 [1 6]
 [2 4]
 [2 6]]


##### How to add a border around a NumPy array?

In [ ]:
import numpy as np
  
array = np.ones((2, 2))
  
print("Initial array:\n", array)
  
print("\n0 on the border and 1 inside the array")

array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print(array)

Initial array:
 [[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


##### How to compare two NumPy arrays?

In [ ]:
import numpy as np

array_1 = np.array([[1,2],[3,4]])
array_2 = np.array([[1,2],[3,4]])

compare = array_1 == array_2
equal_arrays = compare.all()

print(equal_arrays)

True


##### How to check whether specified values are present in NumPy array?

In [ ]:
import numpy as np
  
# creating a Numpy array
array = np.array([[2, 3, 0], [4, 1, 6]])
  
print("Initial array:\n", array )

print('\n2: ',2 in array)
print('0: ',0 in array)
print('10: ',10 in array)

Initial array:
 [[2 3 0]
 [4 1 6]]

2:  True
0:  True
10:  False


##### How to get all 2D diagonals of a 3D NumPy array?


In [ ]:
import numpy as np
  
array = np.arange(3 * 4 * 4).reshape(3, 4, 4)
  
print("Original 3d array:\n", array)
  
diag_array = np.diagonal(array, axis1 = 1, axis2 = 2)
  
print("\n2d diagonal array:\n", diag_array)

Original 3d array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]

2d diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


##### Flatten a Matrix in Python using NumPy

In [ ]:
import numpy as np
  
gfg = np.array([[2, 3], [4, 5]])

print(gfg.flatten())

[2 3 4 5]


##### Flatten a 2d numpy array into 1d array

In [ ]:
import numpy as np
  
array = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
  
print("Initial array:\n", str(array))

result = array.flatten()
  
print("\nNew resulting array: ", result)

Initial array:
 [[1 2 3]
 [2 4 5]
 [1 2 3]]

New resulting array:  [1 2 3 2 4 5 1 2 3]


##### Move axes of an array to new positions

In [ ]:
import numpy as np

x = np.zeros((2, 3, 4))
print("Initial array: \n", x)

print("\nAfter new position:")
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)


Initial array: 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

After new position:
(3, 4, 2)
(4, 2, 3)


#####

```
# This is formatted as code
```

 Interchange two axes of an array

##### NumPy – Fibonacci Series using Binet Formula

In [ ]:
import numpy as np

a = np.arange(1, 11)
lengthA = len(a)

sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(lengthA, Fn))


The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


##### Counts the number of non-zero values in the array


In [ ]:
import numpy as geek

array = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7], [0, 0, 12, 0, 76]]

print ("Non-zero values in array: ", geek.count_nonzero(array))

Non-zero values in array:  8


##### Count the number of elements along a given axis

In [ ]:
import numpy as np
 
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
print("Number of elements: ",np.size(array))

Number of elements:  8


##### Trim the leading and/or trailing zeros from a 1-D array

In [ ]:
import numpy as geek 
  
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
  
print("Trailing zeros: ",geek.trim_zeros(gfg))

Trailing zeros:  [ 1  5  7  0  6  2  9  0 10]


##### Change data type of given numpy array

In [ ]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print("Initial array: ",array)

print("\nArray initial type: ",array.dtype)

array = array.astype('float64')
print("\nArray after change type: ",array)
  
print("\nArray type after change",array.dtype)

Initial array:  [10 20 30 40 50]

Array initial type:  int64

Array after change type:  [10. 20. 30. 40. 50.]

Array type after change float64


##### Reverse a numpy array

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 6, 4, 5])

print("Initial array: ", str(array))

print("\nArray type: ", type(array))

res = array[::-1]

print("\nFinal array", str(res))


Initial array:  [1 2 3 6 4 5]

Array type:  <class 'numpy.ndarray'>

Final array [5 4 6 3 2 1]


##### How to make a NumPy array read-only?

In [ ]:
import numpy as np
  
a = np.zeros(11)
print("Before any change ")
print(a)
  
a[1] = 2
print("Before after first change ")
print(a)
  
a.flags.writeable = False
# a[1] = 7

Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#  Questions on NumPy Matrix

##### Get the maximum value from given matrix


In [ ]:
import numpy as np

x = np.matrix(np.arange(12).reshape((3,4))); 
print("Initial matrix: \n", x)

print("\nMaximum value: ", x.max())

##### Get the minimum value from given matrix


In [ ]:
import numpy as np

x = np.matrix(np.arange(12).reshape((3,4))); 
print("Initial matrix: \n", x)

print("\nMinimum value: ", x.min())

##### Find the number of rows and columns of a given matrix using NumPy


In [ ]:
import numpy as np
    
matrix = np.matrix(np.arange(9).reshape((3, 3)))
  
# Original matrix
print("Initial matrix: \n", matrix)
  
# Number of rows and columns of the said matrix
print("\nNumber of rows and colums: ",matrix.shape)

##### Select the elements from a given matrix


In [ ]:
import numpy as np

matrix = np.matrix(np.arange(9).reshape(3,3))

# x = np.arange(10)
print("Initial matrix: ", matrix )

condlist = [matrix<3, matrix>5]
choicelist = [matrix,matrix]

print("\nElements selected: \n",np.select(condlist, choicelist))


##### Find the sum of values in a matrix


In [ ]:
import numpy as np

x = np.matrix([[1, 2], [4, 3]])
x.sum() 

##### Calculate the sum of the diagonal elements of a NumPy array


In [ ]:
import numpy as np

array = np.array([[55, 25, 15],
					[30, 44, 2],
					[11, 45, 77]])

print("Matrix initial:\n", array)

trace = np.trace(array)
print("\nTrace of given 3X3 matrix: ", trace)


##### Adding and Subtracting Matrices in Python


In [ ]:
import numpy as np


matrix_1 = np.matrix([[3, 4], [1, 2]])
matrix_2 = np.matrix([[6, 7], [4, 5]])

print("First matrix: \n", matrix_1)
print("\nPrinting elements of second matrix: \n", matrix_2)

print("\nAddition of two matrix: ")
print(np.add(matrix_1, matrix_2))

print("\nSubtractinf of two matrix: \n")
print(np.subtract(matrix_2, matrix_1))

##### Ways to add row/columns in numpy array


In [ ]:
import numpy as np

array = np.array([[1,2],[3,4]])
print("Initial array: \n",array)

new_column = [[3], [6]]
array = np.append(array, new_column, axis=1)
print("\nArray with added row/column:\n", array)

##### Matrix Multiplication in NumPy


In [ ]:
import numpy as np

matrix_1 = np.matrix(np.arange(4).reshape((2,2)))
matrix_2 = np.matrix(np.arange(4).reshape((2,2)))

print("Matrix_1: \n", matrix_1)
print("\nMatrix_2: \n", matrix_2)

multiply = np.multiply(matrix_1, matrix_2)
print("\nMultiply matrix: \n", multiply)

##### Get the eigen values of a matrix


In [ ]:
import numpy as np
  
m = np.matrix(np.arange(4).reshape((2,2)))
  
print("Initial Matrix:\n",m)
  
w, v= np.linalg.eig(m)
print("\nEigenvalues:\n",w)
print("\nEigenvectors: \n", v)


##### How to Calculate the determinant of a matrix using NumPy?


In [ ]:
import numpy as np

matrix = np.matrix([[50, 29], [30, 44]])
  
print("Initial matrix: \n", matrix)

det = np.linalg.det(matrix)
  
print("\nDeterminant of matrix: \n", int(det))

##### How to inverse a matrix using NumPy


In [ ]:
import numpy as np

matrix_1 = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])
print("Initial Matrix 1: \n", matrix_1)
print("\nInverse Matrix 1\n", np.linalg.inv(matrix_1))


matrix_2 = np.matrix(np.arange(4).reshape((2,2)))
print("\n\nInitial Matrix 2: \n", matrix_2)
print("\nInverse Matrix 2\n", np.linalg.inv(matrix_2))


##### How to count the frequency of unique values in NumPy array?


In [ ]:
import numpy as np

array = np.array([1, 1, 2, 3, 4, 4, 1])
print("Initial array: ", array)

(unique, counts) = np.unique(array, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print("\nFrequencies: \n",frequencies)

##### Multiply matrices of complex numbers using NumPy in Python


In [ ]:
import numpy as np

matrix_1 = np.matrix([2+3j, 4+5j])
print("First matrix:\n",matrix_1)

matrix_2 = np.matrix([8+7j, 5+6j])
print("\nSecond matrix:\n", matrix_2)

multiply = np.vdot(matrix_1, matrix_2)
print("\nMultiply matrices:\n", multiply)


##### Compute the outer product of two given vectors using NumPy in Python


In [ ]:
import numpy as np

array1 = np.array([6,2])
array2 = np.array([2,5])
print("Array 1:\n", array1, "\nArray 2:\n", array2)

print("\nOuter Product of the two array:")
result = np.outer(array1, array2)
print(result)


##### Calculate inner, outer, and cross products of matrices and vectors using NumPy


In [ ]:
import numpy as np

array1 = np.array([2, 6])
array2 = np.array([3, 10])

print("Array1: ", array1)
print("\nArray2: ", array2)
print("\nInner: ", np.inner(array1, array2))
print("\nOuter: \n", np.outer(array1, array2))
print("\nCross: ", np.cross(array1, array2))

print("\n\n=============")

matrix1 = np.array([[2, 3, 4], [3, 2, 9]])
matrix2 = np.array([[1, 5, 0], [5, 10, 3]])

print("\n\nMatrix1: \n", matrix1)
print("\nMatrix2: \n", matrix2)
print("\nInner: \n", np.inner(matrix1, matrix2))
print("\nOuter: \n", np.outer(matrix1, matrix2))
print("\nCross: \n", np.cross(matrix1, matrix2))



##### Compute the covariance matrix of two given NumPy arrays


In [ ]:
import numpy as np

array1 = np.array([0, 1, 1])
array2 = np.array([2, 2, 1])

print("Array1: ", array1)
print("\nArray2: ", array2)


print("\nCovariance matrix:\n",	np.cov(array1, array2)) 


##### Convert covariance matrix to correlation matrix using Python


In [ ]:
import numpy as np

def correlation_from_covariance(covariance):
    v = np.sqrt(np.diag(covariance))
    outer_v = np.outer(v, v)
    correlation = covariance / outer_v
    correlation[covariance == 0] = 0
    return correlation

##### Compute the Kronecker product of two mulitdimension NumPy arrays


In [ ]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
print('Array1:\n', array1)

array2 = np.array([[5, 6], [7, 8]])
print('\nArray2:\n', array2)

kroneckerProduct = np.kron(array1, array2)
print('\nArray1 x Array2:')
print(kroneckerProduct)


##### Convert the matrix into a list

In [ ]:
import numpy as np
matrix = np.matrix(np.arange(9).reshape((3,3)))

print(matrix.tolist())

# Questions on NumPy Indexing

##### Replace NumPy array elements that doesn’t satisfy the given condition


In [ ]:
import numpy as np

array = np.array([1, 4, 5, 26, 10, 0])

print("Initial array:\n", array)

print("\nReplace all elements of array which are greater than 5 to 30")
array[array > 5] = 30

print("\nNew array :\n", array)


##### Return the indices of elements where the given condition is satisfied


In [ ]:
import numpy as np
  
array = np.array([[2, 3, 4], [5, 8, 10]])

print('Initial array:\n',array)
  
elements = np.where(array < 5)

print ('\nIndices of elements < 5:\n', elements )
print("\nElements which are < 5: \n", array[elements])

##### Replace NaN values with average of columns


In [ ]:
import numpy as np
  
ini_array = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])
  
print ("Initial array:\n", ini_array)
  
col_mean = np.nanmean(ini_array, axis = 0)
  
print ("\nColumns mean: ", str(col_mean))
  
inds = np.where(np.isnan(ini_array))
  
ini_array[inds] = np.take(col_mean, inds[1])
print ("\nFinal array: \n", ini_array)

##### Replace negative value with zero in numpy array


In [ ]:
import numpy as np

array = np.array([1, 2, -3, 4, -5, -6])

print("Initial array", array)

array[array<0] = 0

print("\nNew array: ", array)


##### How to get values of an NumPy array at certain index positions?


In [ ]:
import numpy as np

array1 = np.array([11, 10, 22, 30, 33])
print("Array 1:\n", array1)

array2 = np.array([1, 15, 60])
print("Array 2: \n", array2)

print("\nTake 1 and 15 from Array 2 and put them inst and 5th position of Array 1")

array1.put([0, 4], array2)

print("\nArray :", array1)


##### Find indices of elements equal to zero in a NumPy array


In [ ]:
import numpy as np

array = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])

print("Initial array:\n", array)

res = np.where(array == 0)[0]
print("\nIndices of elements equal to zero: ", res)


##### How to Remove columns in Numpy array that contains non-numeric values?


In [ ]:
import numpy as np

array = np.array([[10.5, 22.5, np.nan], [41, 52.5, np.nan]])

print("Initial array: \n", array)

print("\nRemove all columns containing non-numeric elements ")
print(array[:, ~np.isnan(array).any(axis=0)])


##### How to access different rows of a multidimensional NumPy array?


In [ ]:
import numpy as np

array = np.array([[10, 20, 30],[40, 5, 66],[70, 88, 94]])

print("Given Array :", array)

# Access the First and Last rows of array
res_arr = arr[[0,2]]
print("\nAccessed Rows :")
print(res_arr)


##### Get row numbers of NumPy array having element larger than X


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
				[10, -3, 30, 4, 5],
				[3, 2, 5, -4, 5],
				[9, 7, 3, 6, 5]])

X = 6

print("Initial Array:\n", array)

output = np.where(np.any(array > X, axis = 1))

print("\nResult:\n", output)


##### Get filled the diagonals of NumPy array


In [ ]:
import numpy as np

array = np.zeros((3, 3), int)
print("Initial array:\n", array)

np.fill_diagonal(array, 2)
print("\nFinal array:\n",array)


##### Check elements present in the NumPy array



In [ ]:
import numpy as np

array = np.array([[2, 3, 0],[4, 1, 6]])

print("Initial array:", array)

print("\n2 in array? ",2 in array)
print("\n0 in array? ",0 in array)
print("\n6 in array? ",6 in array)
print("\n50 in array? ",50 in array)
print("\n10 in array? ",10 in array)


##### Combined array index by index 

In [ ]:
import numpy as np
 
array1 = np.array([1, 2, 3, 4, 5, 6]) 
print("Array 1: ", array1)
array2 = np.array([10, 9, 8, 7, 6, 5])
print("\nArray 2: ", array2)
 
print("\nCombinated arrays: ",array1*array2)

# Questions on NumPy Linear Algebra

##### Find a matrix or vector norm using NumPy


In [ ]:
import numpy as np
 
array = np.arange(10)
print("Initial array: ", array)

vec_norm = np.linalg.norm(array) 
print("\nVector norm: ", vec_norm)


##### Calculate the QR decomposition of a given matrix using NumPy


In [ ]:
import numpy as np

matrix1 = np.matrix([[1, 2, 3], [3, 4, 5]])
print('Initial matrix: \n',matrix1)

q, r = np.linalg.qr(matrix1)
print('\nQ:\n', q)
print('\nR:\n', r)

##### Compute the condition number of a given matrix using NumPy


In [ ]:
import numpy as np
  
matrix = np.array([[4, 2], [3, 1]])
  
print("Original matrix:\n", matrix)
  
result =  np.linalg.cond(matrix)
print("\nCondition number of the matrix: ", result)

##### Compute the eigenvalues and right eigenvectors of a given square array using NumPy?


In [ ]:
import numpy as np
  
m = np.array([[1, 2],
              [2, 3]])
  
print("Initial array:\n", m)
  
w, v = np.linalg.eig(m)
  
print("\nEigen values:\n",w)
  
print("\nEigenvectors :\n",v)

##### Calculate the Euclidean distance using NumPy

In [ ]:
import numpy as np

array1 = np.array((1, 2, 3))
array2 = np.array((1, 1, 1))

print("Array 1: ", array1, "\nArray 2: ", array2)

dist = np.linalg.norm(array1 - array2)
print("\nEuclidean distance: ",dist)

# Questions on NumPy Random

##### Create a Numpy array with random values


In [ ]:
import numpy as np

array = np.random.randint(10,90,(4,5))
print("Random array\n", array)


##### How to choose elements from the list with different probability using NumPy?


In [ ]:
import numpy as np

array  = np.array([10, 20, 30, 40, 50])
print("Initial array: \n", array)

number = np.random.choice(num_list)
print("\nValue choice: ",number)


##### How to get weighted random choice in Python?


In [ ]:
import random
  
array = np.array([100, 200, 300, 400, 500])
print("Initial array: ", array)

randomList = random.choices(array, weights=(10, 20, 30, 40, 50), k=5)
print("\nRandom values: ",randomList)

##### Generate Random Numbers From The Uniform Distribution using NumPy


In [ ]:
import numpy as np
  
random_array = np.random.uniform(0.0, 1.0, 5)
  
print("Random values : \n", random_array)

##### Get Random Elements from geometric distribution


In [ ]:
import numpy as np

z = np.random.geometric(p=0.35, size=10000)

print("Geometric distribution : \n", z)

##### Get Random elements from Laplace distribution


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
  
gfg = np.random.laplace(1.45, 15, 1000)
  
count, bins, ignored = plt.hist(gfg, 30, density = True)
# print("Laplace distribution: ", gfg)
plt.show()

##### Return a Matrix of random values from a uniform distribution


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

s = np.random.uniform(-1,0,1000)
# print("Uniform distribution\n", s)

count, bins, ignored = plt.hist(s, 15, density=True)
plt.plot(bins, np.ones_like(bins), linewidth=2, color='r')
plt.show()

##### Return a Matrix of random values from a Gaussian distribution

In [ ]:
import matplotlib.pyplot as plt

mu, sigma = 0, 0.1
s = np.random.normal(mu, sigma, 1000)

abs(mu - np.mean(s))
# abs(sigma - np.std(s, ddof=1))

count, bins, ignored = plt.hist(s, 30, density=True)
plt.plot(bins, 1/(sigma * np.sqrt(2 * np.pi)) *
               np.exp( - (bins - mu)**2 / (2 * sigma**2) ),
         linewidth=2, color='r')
plt.show()

# Questions on NumPy Sorting and Searching

##### How to get the indices of the sorted array using NumPy in Python?


In [ ]:
import numpy as np
  
array = np.array([1, 2, 3, 4, 5])
print("Initial array: ",array)

indices = np.argsort(array)
print("\nIndices: ",indices)

##### Finding the k smallest values of a NumPy array


In [ ]:
import numpy as np
  
array = np.array([23, 12, 1, 3, 4, 5, 6])
print("Initial Array: ", array)
  
k = 4
print("\nK value: ", k)  

arr1 = np.sort(array)
print("\nSmallest elements of the array", arr1[:k])

##### How to get the n-largest values of an array using NumPy?


In [ ]:
import numpy as np
  
array = np.array([2, 0,  1, 5, 4, 1, 9])
  
print("Initial array: ", array)

sorted_index_array = np.argsort(array)
  
sorted_array = array[sorted_index_array]
print("\nSorted array:", sorted_array)
  
n = 1
rslt = sorted_array[-n : ]
print("{}-largest value:".format(n), rslt[0])

n = 2
rslt = sorted_array[-n : ]
print("{}-largest value:".format(n), rslt[0])


##### Sort the values in a matrix


In [ ]:
import numpy as np
             
matrix = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Initial matrix: \n", matrix)

matrix.sort()   
print("\nSort matrix: \n",matrix)

##### Filter out integers from float numpy array


In [ ]:
import numpy as np
  
ini_array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
  
print ("Initial array : ", str(ini_array))
  
result = ini_array[~np.equal(np.mod(ini_array, 1), 0)]
  
print ("\nFinal array : ", str(result))

##### Find the indices into a sorted array

In [ ]:
import numpy as np
  
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Initial array: ",array)
  
indices = np.argsort(array)
print("\nIndices: ",indices)

# Questions on NumPy Mathematics


##### How to get element-wise true division of an array using Numpy?




In [ ]:
import numpy as np
  
x = np.arange(5)
  
print("Initial array:", x)
  
element = np.true_divide(x, 4)
  
print("Element-wise division:", element)

##### How to calculate the element-wise absolute value of NumPy array?


In [ ]:
import numpy as np
  
array = np.array([1, -2, 3])
  
print("Initial array: ", array)

element = np.absolute(array)
  
print("\nAbsolute array: ", element)

##### Compute the negative of the NumPy array


In [ ]:
import numpy as geek

in_num = 10  
print ("Input  number : ", in_num)
    
out_num = geek.negative(in_num) 
print ("negative of input number : ", out_num) 

##### Multiply 2d numpy array corresponding to 1d array


In [ ]:
import numpy as np
  
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array2 = np.array([0, 2, 3])

print("Initial array 1: ", str(array1))
print("\nInitial array 2: ", str(array2))
  
result = array1 * array2[:, np.newaxis]
  
print("\nNew resulting array: \n", result)

##### Computes the inner product of two arrays


In [ ]:
import numpy as np
 
a = [[2, 1], [0, 3]]
b = [[1, 1], [3, 2]]
 
print(np.inner(a, b))

##### Compute the nth percentile of the NumPy array


In [ ]:
import numpy as np
   
array = np.array([20, 2, 7, 1, 34])
print("Initial array : ", array)

print("\n50th percentile of arr : ",np.percentile(arr, 50))
print("25th percentile of arr : ",np.percentile(arr, 25))
print("75th percentile of arr : ",np.percentile(arr, 75))

##### Calculate the n-th order discrete difference along the given axis


In [ ]:
import numpy as geek 
  
arr = geek.array([1, 3, 4, 7, 9])
   
print("Initial array  : ", arr)
print("\nFirst order difference  : ", geek.diff(arr))
print("Second order difference : ", geek.diff(arr, n = 2))
print("Third order difference  : ", geek.diff(arr, n = 3))
print("Fourth order difference  : ", geek.diff(arr, n = 4))

##### Calculate the sum of all columns in a 2D NumPy array


In [ ]:
import numpy as np
  
TwoDList = [[1, 2, 3], [4, 5, 6], 
            [7, 8, 9], [10, 11, 12]]
TwoDArray = np.array(TwoDList)
  
print("2D Array: \n", TwoDArray)
  
print("\nSum: ", np.sum(TwoDArray, axis = 0))

##### Calculate average values of two given NumPy arrays


In [ ]:
import numpy as np
  
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

print("Array 1", arr1)
print("Array 2", arr2)

avg = (arr1 + arr2) / 2
  
print("Average of NumPy arrays: ", avg)

##### How to compute numerical negative value for all elements in a given NumPy array?


In [ ]:
import numpy as np
 
x = np.array([-1, -2, -3, 1, 2, 3, 0])
print("Initial array:", x)
 
r1 = np.negative(x)
print("\nNegative value of the given array:", r1)

##### How to get the floor, ceiling and truncated values of the elements of a numpy array?


In [ ]:
import numpy as np
  
array = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
  
floor = np.floor(array)
print("Floor: ",floor)
  
ceil = np.ceil(array)
print("Ceil: ", ceil)

trunc = np.trunc(array)
print("Trincated: ", trunc)

##### How to round elements of the NumPy array to the nearest integer?


In [ ]:
import numpy as n
  
y = n.array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
print("Initial array:", y , end=" ")
  
y = n.rint(y)
print("\nAfter round:", y, end=" ")

##### Find the round off the values of the given matrix


In [ ]:
import numpy as np
           
matrix = np.matrix('[1.2, 2.3; 4.7, 5.5; 7.2, 8.9]')
           
geeks = matrix.round()
     
print(geeks)

##### Determine the positive square-root of an array


In [ ]:
import numpy as geek 
  
arr1 = geek.sqrt([1, 4, 9, 16])
arr2 = geek.sqrt([6, 10, 18])

print("Initial array 1", arr1)
print("Initial array 2", arr2)
  
print("\nSquare-root of an array1  : ", arr1)
print("Square-root of an array2  : ", arr2)

##### Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

In [ ]:
import numpy as np
  
matrix1 = np.array([[1, 2], [0, 2]])
matrix2 = np.array([[0, 1], [3, 4]])
  
print("Original matrix 1: \n", matrix1)
print("\nOriginal matrix 2: \n", matrix2)

  
result = np.einsum("mk,kn", matrix1, matrix2)
  
print("\nEinstein’s summation convention of the two matrix:\n",result)

# Questions on NumPy Statistics


##### Compute the median of the flattened NumPy array


In [ ]:
import numpy as np
  
array = np.array([1, 2, 3, 4, 5, 6, 7])
print("\nInitial array: ", array)
  
med_array = np.median(array)
print("\nMedian of the flattened:", med_array)

##### Find Mean of a List of Numpy Array


In [ ]:
import numpy as np
  
Input = [np.array([1, 2, 3]),
         np.array([4, 5, 6]),
         np.array([7, 8, 9])]
  
Output = []
  
for i in range(len(Input)):
   Output.append(np.mean(Input[i]))
  
print("Mean: ",Output)

##### Calculate the mean of array ignoring the NaN value


In [ ]:
import numpy as np
   
array = np.array([[20, 15, 37], [47, 13, np.nan]])
print("Initial array: \n", array)

print("\nShape of array: ", array.shape)
   
print("\nMean of array without nanmean :", np.mean(array))
   
print("\nUsing nanmean:", np.nanmean(array))

##### Get the mean value from given matrix


In [ ]:
import numpy as np
          
matrix = np.matrix('[64, 1; 12, 3]')
print("Initial matrix: \n",matrix )
geeks = matrix.mean()
    
print("Mean value: ",geeks)

##### Compute the variance of the NumPy array


In [ ]:
import numpy as np 
      
array = np.array([20, 2, 7, 1, 34]) 
  
print("Initial array : ", array) 
print("Variance of array : ", np.var(array)) 


##### Compute the standard deviation of the NumPy array


In [ ]:
import numpy as np

array = [20, 2, 7, 1, 34]
  
print("Initial array : ", array) 
print("Standard of array : ", np.std(array))

##### Compute pearson product-moment correlation coefficients of two given NumPy arrays


In [ ]:
import numpy as np
  
array1 = np.array([ 2, 4, 8])
array2 = np.array([ 3, 2,1])
  
print("Array 1: ", array1)  
print("Array 2: ", array2)  

rslt2 = np.corrcoef(array1, array2)
  
print("\nCorrelation coefficients: \n",rslt2)

##### Calculate the mean across dimension in a 2D NumPy array


In [ ]:
import numpy as np
  
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
  
row_mean = np.mean(arr, axis =1)
  
row1_mean = row_mean[0]
print("Mean of Row 1: ", row1_mean)
  
row2_mean = row_mean[1]
print("Mean of Row 2: ", row2_mean)
  
row3_mean = row_mean[2]
print("Mean of Row 3: ", row3_mean)
print("----------------------")
  
column_mean = np.mean(arr, axis=0)
  
column1_mean = column_mean[0]
print("Mean of column 1: ", column1_mean)
  
column2_mean = column_mean[1]
print("Mean of column 2: ", column2_mean)
  
column3_mean = column_mean[2]
print("Mean of column 3: ", column3_mean)

##### Calculate the average, variance and standard deviation in Python using NumPy


In [ ]:
import numpy as np
  
array = np.array([2, 4, 4, 4, 5, 5, 7, 9])
  
print("Average: ",np.average(array))
print("Variance: ",np.var(array))
print("Standard deviation: ",np.std(array))

##### Describe a NumPy Array in Python

In [ ]:
import numpy as np  
  
array = np.array([4, 5, 8, 5, 6, 4, 9, 2, 4, 3, 6])    
  
mean = np.mean(array)
median = np.median(array)
min = np.amin(array)
max = np.amax(array)
range = np.ptp(array)
varience = np.var(array)
sd = np.std(array)
  
print("Descriptive analysis\n\n")
print("Initial Array =", array)
print("Measures of Central Tendency")
print("Mean =", mean)
print("Median =", median)
print("Measures of Dispersion")
print("Minimum =", min)
print("Maximum =", max)
print("Range =", range)
print("Variance =", varience)
print("Standard Deviation =", sd)

# Questions on Polynomial


##### Define a polynomial function


In [ ]:
import numpy as np
  
p1 = np.poly1d([1, 2])
p2 = np.poly1d([4, 9, 5, 4])
  
print ("P1 : ", p1)
print ("\n p2 : ", p2)
  
print ("\n\np1 at x = 2 : ", p1(2))
print ("p2 at x = 2 : ", p2(2))
  
print ("\n\nRoots of P1 : ", p1.r)
print ("Roots of P2 : ", p2.r)
  
print ("\n\nCoefficients of P1 : ", p1.c)
print ("Coefficients of P2 : ", p2.coeffs)
  
print ("\n\nOrder / Degree of P1 : ", p1.o)
print ("Order / Degree of P2 : ", p2.order)

##### How to add one polynomial to another using NumPy in Python?


In [ ]:
import numpy

px = (5,-2,5)
print("Polynomial 1: ", px)
qx = (2,-5,2)
print("Polynomial 2: ", qx)
  
rx = numpy.polynomial.polynomial.polyadd(px,qx)
  
print("Result add: ",rx)

##### How to subtract one polynomial to another using NumPy in Python?


In [ ]:
import numpy as np

px = (5,-2,5)
print("Polynomial 1: ", px)

qx = (2,-5,2)
print("Polynomial 2: ", qx)

rx = numpy.polynomial.polynomial.polysub(px,qx)
  
print("Subtract: ",rx)

##### How to multiply a polynomial to another using NumPy in Python?


In [ ]:
import numpy as np

px = (5,-2,5)
print("Polynomial 1: ", px)

qx = (2,-5,2)
print("Polynomial 2: ", qx)

rx = numpy.polynomial.polynomial.polymul(px,qx)

print("Multiply: ",rx)

##### How to divide a polynomial to another using NumPy in Python?


In [ ]:
import numpy as np

px = (5,-2,5)
print("Polynomial 1: ", px)

gx = (2,-5,2)
print("Polynomial 2: ", qx)

qx, rx = numpy.polynomial.polynomial.polydiv(px,gx)

print("Divide: ",qx,"\n",rx)

##### Find the roots of the polynomials using NumPy


In [ ]:
import numpy as np
  
coeff = np.array([1, 3, 2, 1])
print("Roots: \n",np.roots(coeff))

##### Evaluate a 2-D polynomial series on the Cartesian product


In [ ]:
import numpy as np 
from numpy.polynomial.polynomial import polygrid2d
  
c = np.array([[1, 3, 5], [2, 4, 6]]) 
  
ans = polygrid2d([7, 9], [8, 10], c)
print("Result: \n",ans)

##### Evaluate a 3-D polynomial series on the Cartesian product

In [ ]:
import numpy as np 
from numpy.polynomial.polynomial import polygrid3d
  
c = np.array([[1, 3, 5], [2, 4, 6], [10, 11, 12]]) 
  
ans = polygrid3d([7, 9], [8, 10], [5, 6], c)
print("Result: \n",ans)

# Questions on NumPy Strings

##### Repeat all the elements of a NumPy array of strings


In [ ]:
import numpy as np
  
array = np.array(['Kelly', 'Bianca', 'Tiago', 'Vieira', 'UFAL'], dtype = np.str)
print("Initial Array :", array)
  
new_array = np.char.multiply(array, 3)
print("\nNew array :\n", new_array)

##### How to split the element of a given NumPy array with spaces?


In [ ]:
import numpy as np
  
array = np.array(['Linguagens de programação PHP C# Python C Java C++'], dtype=np.str)
print("Initial array: ",array)
  
split = np.char.split(array)
print("Split elements: \n",split)

##### How to insert a space between characters of all the elements of a given NumPy array?


In [ ]:
import numpy as np
  
array = np.array(["Kelly", "Bianca", "Araujo"], dtype=np.str)
print("Initial Array: ", array)
  
r = np.char.join(" ", array)
print("Array with spaces between characters \n",r )

##### Find the length of each string element in the Numpy array


In [ ]:
import numpy as np
  
arr = np.array(['Kelly', 'Bianca', 'Araujo', 'Silva', 'Instituto de computação'])

print("Initial array: ", arr)

length_checker = np.vectorize(len)
  
arr_len = length_checker(arr)
  
print("Lenght of each string: ", arr_len)

##### Swap the case of an array of string


In [ ]:
import numpy as np 
  
array = np.array(['KELLY', 'tiago', 'UfAl', 'Silva'])
print ("Initial array : ", array)
  
swap = np.char.swapcase(array)
print ("Swapcasecased :", swap)

##### Change the case to uppercase of elements of an array


In [ ]:
import numpy as np
 
print(np.char.upper(['kelly', 'bianca', 'ufal']))
 

##### Change the case to lowercase of elements of an array


In [ ]:
import numpy as np
 
print(np.char.lower(['KELLY', 'BIANCA', 'UFAL']))

##### Join String by a seperator


In [ ]:
import numpy as np
  
array = np.array(['Python', 'Numpy', 'Pandas'])
print ("Inicial array : ", array) 
  
sep = np.array(['-', '+', '*'])
  
out_arr = np.core.defchararray.join(sep, array)
print ("Array with separator: ", out_arr) 

##### Check if two same shaped string arrayss one by one


In [ ]:
import numpy as geek
  
array1 = geek.array('numpy')
print ("Array 1: ", array1)
  
array2 = geek.array('numpy')
print ("Array 2: ", array2)  
  
out_arr = geek.char.equal(array1, array2)
print ("Output array: ", out_arr)

##### Count the number of substrings in an array


In [ ]:
import numpy as np
  
array = np.array(['banana', '  cana', 'navio'])
print("Initial array : ", array) 
  
count = np.char.count(array, sub ='an')
print("Number of substrings (an) in array: ", count) 

##### Find the lowest index of the substring in an array


In [ ]:
import numpy as np 
  
arr = ['vdsdsttetteteAAAa', 'AAAAAAAaattttds', 'AAaaxxxxtt', 'AAaaXDSDdscz']
  
print ("arr : ", arr)
  
print ("\nfind of 'tt'", np.char.find(arr, 'tt'))
print ("find of 'tt'", np.char.find(arr, 'tt', start = 0))
print ("find of 'tt'", np.char.find(arr, 'tt', start = 8))

##### Get the boolean array when values end with a particular character


In [ ]:
import numpy as np
  
array = np.array(['alagoas', 'varal', 'sal'])
print("Initial array: ", array)

find = np.char.endswith(array, 'al')
print("Values with 'al' in the final",find)

##### [More Questions on NumPy](https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/) 


##### Different ways to convert a Python dictionary to a NumPy array


In [ ]:
import numpy as np
  
dict_created = {0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216}
  
print("Inicial type: ",type(dict_created))

res_array = np.array(list(dict_created.items()))
  
print(res_array)
  
print("After convert type: ",type(res_array))

##### How to convert a list and tuple into NumPy arrays?


In [ ]:
import numpy as np
  
list1 = [1, 2, 3]
print("Type: ",type(list1), "\n", list1, "\n")

array1 = np.array(list1)
print("Convert list to array",type(array1), "\n", array1, "\n")
  
tuple1 = ((1, 2, 3))
print("Type: ",type(tuple1),"\n",tuple1,"\n")

array2 = np.array(tuple1)
print("Convert tuple to array",type(array2),"\n", array2, "\n")
  
array3 = np.array([tuple1, list1, array2])
print("Type: ",type(array3), "\n", array3)

##### Ways to convert array of strings to array of floats


In [ ]:
import numpy as np
  
ini_array = np.array(["1.1", "1.5", "2.7", "8.9"])
  
print ("Iinitial array", str(ini_array))

res = ini_array.astype(np.float)
  
print ("Final array", str(res))

##### Convert a NumPy array into a csv file


In [ ]:
import numpy as np
  
arr = np.arange(1,11)
  
print(arr)

arr.tofile('data.csv', sep = ',')

##### How to Convert an image to NumPy array and save it to CSV file using Python?


In [ ]:
from PIL import Image
import numpy as gfg

img = Image.open('number.png')

imageToMatrice = gfg.asarray(img)

print(imageToMatrice.shape)


##### How to save a NumPy array to a text file?


In [ ]:
import numpy as np

List = [1, 2, 3, 4, 5]
Array = np.array(List)

print('Array:\n', Array)

np.savetxt("file1.txt", Array)

content = np.loadtxt('file1.txt')
print("\nContent in file1.txt:\n", content)


##### Load data from a text file


In [ ]:
import numpy as np
  
File_data = np.loadtxt("file2.txt", dtype=int)
print(File_data)

##### Plot line graph from NumPy array


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
 
x = np.arange(1, 11)
y = x * x
 
plt.title("Line graph")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.plot(x, y, color ="red")
plt.show()

##### Create Histogram using NumPy

In [ ]:
from matplotlib import pyplot as plt
import numpy as np

a = np.random.randint(100, size =(50))

fig = plt.figure(figsize =(10, 7))

plt.hist(a, bins = [0, 10, 20, 30,
					40, 50, 60, 70,
					80, 90, 100])

plt.title("Numpy Histogram")
plt.show()
